package ru.almaz.caravelletravelsreborn.presentation.bot;

public enum BotExceptions {
    TEXT_NOT_FOUND,
    INVALID_ID,

    // USER
    USER_NOT_FOUND,
    NO_PERMISSION,
    INVALID_RESET_TOKEN,
    INVALID_CREDENTIALS,
    EMAIL_USED,
    INVALID_PASSWORD,
    INVALID_EMAIL,

    // BOOKING
    BOOKING_EXIST,
    INVALID_DATE,
    BOOKING_NOT_FOUND,
    USER_NOT_CREATOR_OF_BOOKING,
    BOOKING_NOT_FILLED,
    BOOKING_ALREADY_COMMITTED,
    INVALID_PHONE,
    INVALID_PASS_COUNT,

    // UNEXPECTED UNHANDLED EXCEPTIONS
    UNHANDLED_USECASE_EXCEPTION,
    UNHANDLED_PRESENTATION_EXCEPTION,
    UNEXPECTED_EXCEPTION
}
